"""Reproducibility freeze and release packager.

``exonym freeze`` builds a frozen reproducibility bundle under
``candidate/<id>/releases/<version>/`` containing pinned dependency locks,
container image definitions, and a content-addressed manifest.

The manifest records every engine-run.json generated during the candidate
analysis, every transit configuration hash, and the repository pyproject.toml
hash so that the full analysis chain is reproductively traceable from a single
``manifest.json`` file.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional
from uuid import uuid4

from .workspace import CandidateWorkspace, METADATA_FILENAME


_RELEASE_VERSION = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")
_RESERVED_WINDOWS_NAMES = {
    "CON", "PRN", "AUX", "NUL",
    *("COM{0}".format(index) for index in range(1, 10)),
    *("LPT{0}".format(index) for index in range(1, 10)),
}

DOCKERFILE_TEMPLATE = """# EXONYM reproducibility image
# Generated by exonym freeze for {{CANDIDATE_ID}}.
FROM python:3.9-slim
WORKDIR /work
COPY requirements.lock.txt /work/requirements.lock.txt
COPY source /work/source
COPY workspace /work/workspace
RUN pip install --no-cache-dir -r /work/requirements.lock.txt && \
    pip install --no-cache-dir --no-deps /work/source
CMD ["exonym", "--root", "/work/workspace", "verify"]
"""

APPTAINER_TEMPLATE = """# EXONYM reproducibility definition
# Generated by exonym freeze for {{CANDIDATE_ID}}.
Bootstrap: docker
From: python:3.9-slim

%files
    requirements.lock.txt /work/requirements.lock.txt
    source /work/source
    workspace /work/workspace

%post
    apt-get update && apt-get install -y --no-install-recommends git
    pip install --no-cache-dir -r /work/requirements.lock.txt
    pip install --no-cache-dir --no-deps /work/source

%runscript
    exec exonym --root /work/workspace verify
"""

ENVIRONMENT_TEMPLATE = """name: exonym-freeze-{{CANDIDATE_ID}}
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - pip
  - pip:
{pip_entries}
"""

RELEASE_README_TEMPLATE = """# EXONYM reproducibility release

This candidate-local release preserves the source and evidence state used for
the recorded analysis.

- `source/` contains the packaged source snapshot used by the container files.
- `workspace/` is a root-shaped snapshot; run commands with `--root workspace`.
- `manifest.json` lists SHA-256 digests for every frozen payload file.
- `requirements.lock.txt`, `environment.lock.yml`, `Dockerfile`, and
  `Apptainer.def` define the replay environment.

The snapshot intentionally excludes `scratch/` and prior `releases/` because
they are ephemeral or recursively derived. It contains no claim that an
optional scientific backend is installed or that an external service can be
replayed without its recorded local response.
"""

_WORKSPACE_SNAPSHOT_EXCLUDES = {"releases", "scratch", "__pycache__"}


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _git_commit(repository_root: Path) -> str:
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repository_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return "unknown"


def _default_version() -> str:
    return "release-" + _now().replace(":", "").replace("-", "")[:15]


def _validate_release_version(version: str) -> str:
    """Validate a directory-safe, lowercase release version label."""
    normalized = version.strip().lower()
    if not _RELEASE_VERSION.fullmatch(normalized):
        raise ValueError(
            "release version must use lowercase letters, numbers, dots, hyphens, or underscores"
        )
    if normalized.endswith(".") or normalized.split(".")[0].upper() in _RESERVED_WINDOWS_NAMES:
        raise ValueError("release version is not a safe directory name")
    return normalized


def _collect_engine_manifests(workspace: CandidateWorkspace) -> List[Dict]:
    """Scan candidate runs/ and return a sorted list of engine-run manifest records.

    Each record contains:
    - ``engine``: the engine name from the manifest
    - ``run_id``: the run identifier
    - ``status``: succeeded / failed
    - ``manifest_path``: relative posix path from workspace root
    - ``sha256``: content hash of the manifest file

    Records are ordered by ``started_at`` ascending so that the release manifest
    reflects the full chronological analysis chain.
    """
    records: List[Dict] = []
    runs_dir = workspace.path / "runs"
    if not runs_dir.is_dir():
        return records

    for manifest_path in sorted(runs_dir.glob("*/*/engine-run.json")):
        if not manifest_path.is_file():
            continue
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        records.append({
            "engine": data.get("engine", "unknown"),
            "run_id": data.get("run_id", ""),
            "status": data.get("status", "unknown"),
            "started_at": data.get("started_at", ""),
            "manifest_path": manifest_path.relative_to(workspace.path).as_posix(),
            "sha256": _sha256(manifest_path),
        })

    # Sort by started_at timestamp so the chain is chronological
    records.sort(key=lambda r: r.get("started_at", ""))
    return records


def _collect_config_hashes(workspace: CandidateWorkspace) -> Dict[str, str]:
    """Hash every JSON file under candidate config/ and return a path→sha256 mapping.

    Config files contain the transit ephemeris priors that were active during the
    analysis. Including their hashes in the freeze manifest makes it possible to
    detect any ephemeris drift between the original run and a replay attempt.
    """
    hashes: Dict[str, str] = {}
    config_dir = workspace.path / "config"
    if not config_dir.is_dir():
        return hashes
    for p in sorted(config_dir.rglob("*.json")):
        if p.is_file():
            rel = p.relative_to(workspace.path).as_posix()
            hashes[rel] = _sha256(p)
    return hashes


def _collect_catalog_manifests(workspace: CandidateWorkspace) -> List[Dict]:
    """Index append-only catalog retrieval manifests for release reproducibility."""
    records: List[Dict] = []
    for manifest_path in sorted((workspace.path / "runs" / "catalog").glob("*/*/query-manifest.json")):
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError):
            continue
        if not isinstance(data, dict):
            continue
        records.append({
            "provider": data.get("provider", "unknown"),
            "retrieval_id": data.get("retrieval_id", ""),
            "status": data.get("status", "unknown"),
            "retrieved_at": data.get("retrieved_at", ""),
            "manifest_path": manifest_path.relative_to(workspace.path).as_posix(),
            "sha256": _sha256(manifest_path),
        })
    records.sort(key=lambda record: record.get("retrieved_at", ""))
    return records


def _require_valid_catalog_evidence(workspace: CandidateWorkspace) -> None:
    """Refuse to freeze candidate catalog evidence that fails repository validation."""
    catalog_runs = workspace.path / "runs" / "catalog"
    if not catalog_runs.is_dir():
        return
    from .isolation import IsolationReport
    from .schemas import validate_schemas

    report = IsolationReport()
    validate_schemas(workspace.repository_root, report)
    workspace_root = workspace.path.resolve()
    failures = []
    for violation in report.violations:
        try:
            path = Path(violation.path).resolve()
            path.relative_to(workspace_root)
        except (TypeError, ValueError):
            continue
        if "catalog" in path.parts:
            failures.append(violation)
    if failures:
        raise ValueError("cannot freeze invalid candidate-local catalog evidence: {0}".format(failures[0].detail))


def _copy_tree(source: Path, destination: Path, ignore=None) -> None:
    """Copy a source tree without sharing mutable files with the release."""
    shutil.copytree(source, destination, copy_function=shutil.copy2, ignore=ignore)


def _snapshot_source(repository_root: Path, bundle_dir: Path) -> Dict[str, object]:
    """Copy the exact package source required by generated replay environments."""
    pyproject = repository_root / "pyproject.toml"
    source_tree = repository_root / "src"
    if not pyproject.is_file() or not source_tree.is_dir():
        raise FileNotFoundError(
            "self-contained freeze requires repository pyproject.toml and src/"
        )
    destination = bundle_dir / "source"
    destination.mkdir()
    shutil.copy2(pyproject, destination / "pyproject.toml")
    _copy_tree(source_tree, destination / "src")
    for name in ("README.md", "LICENSE", "LICENSE.md"):
        source = repository_root / name
        if source.is_file():
            shutil.copy2(source, destination / name)
    return {
        "path": "source",
        "package_definition": "source/pyproject.toml",
        "package_source": "source/src",
    }


def _snapshot_workspace(workspace: CandidateWorkspace, repository_root: Path, bundle_dir: Path) -> Dict[str, object]:
    """Copy a root-shaped candidate evidence snapshot without recursive releases."""
    destination = bundle_dir / "workspace"
    candidate_destination = destination / "candidate" / workspace.candidate_id
    candidate_destination.parent.mkdir(parents=True)

    def ignore_snapshot_entries(_directory: str, names: List[str]) -> List[str]:
        return [name for name in names if name in _WORKSPACE_SNAPSHOT_EXCLUDES]

    _copy_tree(workspace.path, candidate_destination, ignore=ignore_snapshot_entries)
    for resource_name in ("schemas", "templates"):
        source = repository_root / resource_name
        if source.is_dir():
            _copy_tree(source, destination / resource_name)
    return {
        "path": "workspace",
        "candidate_path": "workspace/candidate/{0}".format(workspace.candidate_id),
        "excluded_paths": sorted(_WORKSPACE_SNAPSHOT_EXCLUDES),
    }


def freeze(workspace: CandidateWorkspace, version: Optional[str] = None) -> Path:
    """Build the reproducibility bundle and return its directory.

    The release manifest includes:
    - Pinned dependency lock file hashes
    - Git commit at freeze time
    - candidate.json hash
    - Engine run manifest index (all runs/<engine>/<run-id>/engine-run.json)
    - Transit config file hashes (config/**/*.json)
    - pyproject.toml hash (repository-level package definition)
    """
    version = _validate_release_version(version or _default_version())
    release_dir = workspace.path / "releases" / version
    if release_dir.exists():
        raise FileExistsError("release already exists: {0}".format(release_dir))
    repository_root = workspace.repository_root
    lock_source = repository_root / "requirements-lock.txt"
    if not lock_source.is_file():
        raise FileNotFoundError("root requirements-lock.txt not found: {0}".format(lock_source))
    _require_valid_catalog_evidence(workspace)
    bundle_dir = release_dir.parent / ".{0}.staging-{1}".format(version, uuid4().hex)
    bundle_dir.mkdir(parents=True)
    try:
        shutil.copyfile(lock_source, bundle_dir / "requirements.lock.txt")
        source_snapshot = _snapshot_source(repository_root, bundle_dir)
        workspace_snapshot = _snapshot_workspace(workspace, repository_root, bundle_dir)
        (bundle_dir / "README.md").write_text(RELEASE_README_TEMPLATE, encoding="utf-8")

        pip_entries = []
        for line in lock_source.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                pip_entries.append('      - "{0}"'.format(line))
        pip_entries.append('      - "-e ./source"')
        environment = (
            ENVIRONMENT_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
            .replace("{pip_entries}", "\n".join(pip_entries))
        )
        (bundle_dir / "environment.lock.yml").write_text(environment, encoding="utf-8")

        dockerfile = DOCKERFILE_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
        (bundle_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")
        apptainer = APPTAINER_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
        (bundle_dir / "Apptainer.def").write_text(apptainer, encoding="utf-8")

        metadata_path = workspace.path / METADATA_FILENAME
        files: List[Dict] = []
        for path in sorted(bundle_dir.rglob("*")):
            if path.is_file():
                files.append(
                    {
                        "path": path.relative_to(bundle_dir).as_posix(),
                        "size_bytes": path.stat().st_size,
                        "sha256": _sha256(path),
                    }
                )

        manifest = {
            "schema": "exonym-freeze-2",
            "version": version,
            "candidate_id": workspace.candidate_id,
            "frozen_at": _now(),
            "git_commit": _git_commit(repository_root),
            "candidate_json_sha256": _sha256(metadata_path),
            "engine_manifests": _collect_engine_manifests(workspace),
            "config_hashes": _collect_config_hashes(workspace),
            "catalog_manifests": _collect_catalog_manifests(workspace),
            "pyproject_toml_sha256": _sha256(repository_root / "pyproject.toml"),
            "requirements_lock_sha256": _sha256(lock_source),
            "replay_status": "self-contained-source-and-candidate-evidence-snapshot",
            "source_snapshot": source_snapshot,
            "workspace_snapshot": workspace_snapshot,
            "files": files,
        }
        (bundle_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        bundle_dir.replace(release_dir)
    except Exception:
        shutil.rmtree(bundle_dir, ignore_errors=True)
        raise
    return release_dir
