"""Reproducibility freeze and release packager.

``exonym freeze`` builds a frozen reproducibility bundle under
``candidate/<id>/releases/<version>/`` containing pinned dependency locks,
container image definitions, and a content-addressed manifest.

The manifest records every engine-run.json generated during the candidate
analysis, every transit configuration hash, and the repository pyproject.toml
hash so that the full analysis chain is reproducibly traceable from a single
``manifest.json`` file.

A release verifies byte integrity and an offline source/workspace load
boundary. It intentionally does not reproduce scientific engines, network
retrievals, or remote services.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional
from uuid import uuid4

from .workspace import CandidateWorkspace, METADATA_FILENAME


_RELEASE_VERSION = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")
_SHA256_HEX = re.compile(r"^[0-9a-f]{64}$")
_PINNED_REQUIREMENT = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[A-Za-z0-9][A-Za-z0-9._+!\-]*)$"
)
_RESERVED_WINDOWS_NAMES = {
    "CON", "PRN", "AUX", "NUL",
    *("COM{0}".format(index) for index in range(1, 10)),
    *("LPT{0}".format(index) for index in range(1, 10)),
}

MANIFEST_FILENAME = "manifest.json"
MANIFEST_DIGEST_FILENAME = "manifest.sha256"
REQUIREMENTS_LOCK_FILENAME = "requirements.lock.txt"

DOCKERFILE_TEMPLATE = """# EXONYM reproducibility image
# Generated by exonym freeze for {{CANDIDATE_ID}}.
FROM python:3.9-slim
WORKDIR /work
COPY requirements.lock.txt /work/requirements.lock.txt
COPY source /work/source
COPY workspace /work/workspace
RUN pip install --no-cache-dir -r /work/requirements.lock.txt && \
    pip install --no-cache-dir --no-build-isolation --no-deps /work/source
CMD ["exonym", "--root", "/work/workspace", "verify"]
"""

APPTAINER_TEMPLATE = """# EXONYM reproducibility definition
# Generated by exonym freeze for {{CANDIDATE_ID}}.
Bootstrap: docker
From: python:3.9-slim

%files
    requirements.lock.txt /work/requirements.lock.txt
    source /work/source
    workspace /work/workspace

%post
    apt-get update && apt-get install -y --no-install-recommends git
    pip install --no-cache-dir -r /work/requirements.lock.txt
    pip install --no-cache-dir --no-build-isolation --no-deps /work/source

%runscript
    exec exonym --root /work/workspace verify
"""

ENVIRONMENT_TEMPLATE = """name: exonym-freeze-{{CANDIDATE_ID}}
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - pip
  - pip:
{pip_entries}
"""

RELEASE_README_TEMPLATE = """# EXONYM reproducibility release

This candidate-local release preserves the source and evidence state used for
the recorded analysis.

- `source/` contains the packaged source snapshot used by the container files.
- `workspace/` is a root-shaped snapshot; run commands with `--root workspace`.
- `manifest.json` lists SHA-256 digests for every frozen payload file and
  `manifest.sha256` is its detached integrity digest.
- `requirements.lock.txt`, `environment.lock.yml`, `Dockerfile`, and
  `Apptainer.def` define the replay environment.

Run `exonym verify-release <candidate-id> --version <version>` from the
repository root to check the detached digest and inventory, then import the
frozen source in a separate Python process and load its frozen workspace. It
does not re-run scientific engines, network retrievals, or remote services.

The snapshot intentionally excludes `scratch/` and prior `releases/` because
they are ephemeral or recursively derived. It contains no claim that an
optional scientific backend is installed or that an external service can be
replayed without its recorded local response.
"""

_WORKSPACE_SNAPSHOT_EXCLUDES = {"releases", "scratch", "__pycache__"}


class ReleaseVerificationError(RuntimeError):
    """Raised when a frozen release fails an integrity or replay check.

    The exception describes a frozen-bundle contract failure; it is not a
    scientific assessment of the candidate or its evidence.
    """


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _git_commit(repository_root: Path) -> str:
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repository_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return "unknown"


def _default_version() -> str:
    return "release-" + _now().replace(":", "").replace("-", "")[:15]


def _validate_release_version(version: str) -> str:
    """Validate a directory-safe, lowercase release version label."""
    normalized = version.strip().lower()
    if not _RELEASE_VERSION.fullmatch(normalized):
        raise ValueError(
            "release version must use lowercase letters, numbers, dots, hyphens, or underscores"
        )
    if normalized.endswith(".") or normalized.split(".")[0].upper() in _RESERVED_WINDOWS_NAMES:
        raise ValueError("release version is not a safe directory name")
    return normalized


def _read_pinned_requirements(lock_path: Path) -> List[str]:
    """Return a normalized, exact-version requirements lock inventory.

    A release lock is deliberately a plain requirements file so the generated
    Docker and Apptainer definitions can install it with stock pip. Every
    active line must therefore be an exact ``distribution==version`` pin; URLs,
    editable installs, constraints, and resolver options would leave part of
    the replay environment outside the frozen inventory.
    """
    packages: List[str] = []
    seen = set()
    for line_number, raw_line in enumerate(
        lock_path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = _PINNED_REQUIREMENT.fullmatch(line)
        if match is None:
            raise ValueError(
                "requirements lock line {0} must be an exact distribution==version pin".format(
                    line_number
                )
            )
        normalized_name = match.group("name").lower().replace("_", "-").replace(".", "-")
        if normalized_name in seen:
            raise ValueError("requirements lock contains a duplicate distribution: {0}".format(match.group("name")))
        seen.add(normalized_name)
        packages.append(line)
    if not packages:
        raise ValueError("requirements lock has no pinned distributions")
    return packages


def _read_release_manifest(path: Path) -> Dict[str, object]:
    """Read release JSON strictly, including duplicate-key and non-finite rejection."""
    def reject_constant(value: str) -> object:
        raise ValueError("non-finite JSON constant is not permitted: {0}".format(value))

    def reject_duplicate_keys(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError("duplicate JSON key: {0}".format(key))
            result[key] = value
        return result

    try:
        value = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=reject_duplicate_keys,
            parse_constant=reject_constant,
        )
    except (OSError, UnicodeError, ValueError, json.JSONDecodeError) as exc:
        raise ReleaseVerificationError("release manifest is unreadable: {0}".format(exc)) from exc
    if not isinstance(value, dict):
        raise ReleaseVerificationError("release manifest must be a JSON object")
    return value


def _release_member_path(release_dir: Path, relative_path: object) -> Optional[Path]:
    """Resolve one bundle member only when it stays within the release root."""
    if not isinstance(relative_path, str) or not relative_path:
        return None
    candidate = Path(relative_path)
    if candidate.is_absolute() or ".." in candidate.parts:
        return None
    release_root = release_dir.resolve()
    member = (release_root / candidate).resolve()
    try:
        member.relative_to(release_root)
    except ValueError:
        return None
    return member


def _verify_detached_manifest_digest(release_dir: Path) -> str:
    """Validate the canonical detached SHA-256 digest of ``manifest.json``."""
    manifest_path = release_dir / MANIFEST_FILENAME
    digest_path = release_dir / MANIFEST_DIGEST_FILENAME
    if not manifest_path.is_file() or manifest_path.is_symlink():
        raise ReleaseVerificationError("release has no regular manifest.json")
    if not digest_path.is_file() or digest_path.is_symlink():
        raise ReleaseVerificationError("release has no regular manifest.sha256")
    try:
        fields = digest_path.read_text(encoding="ascii").split()
    except (OSError, UnicodeError) as exc:
        raise ReleaseVerificationError("release manifest digest is unreadable: {0}".format(exc)) from exc
    if len(fields) != 2 or fields[1] != MANIFEST_FILENAME or _SHA256_HEX.fullmatch(fields[0]) is None:
        raise ReleaseVerificationError("release manifest digest must contain '<sha256>  manifest.json'")
    actual = _sha256(manifest_path)
    if fields[0] != actual:
        raise ReleaseVerificationError("release manifest detached SHA-256 does not match manifest.json")
    return actual


def _verify_release_inventory(release_dir: Path, manifest: Dict[str, object]) -> int:
    """Verify every payload file exactly once without trusting the manifest path."""
    files = manifest.get("files")
    if not isinstance(files, list):
        raise ReleaseVerificationError("release manifest files must be an array")
    expected_paths = set()
    for entry in files:
        if not isinstance(entry, dict):
            raise ReleaseVerificationError("release manifest file entry must be an object")
        relative_path = entry.get("path")
        member = _release_member_path(release_dir, relative_path)
        if member is None or not member.is_file() or member.is_symlink():
            raise ReleaseVerificationError("release manifest references a missing, unsafe, or linked file")
        if not isinstance(relative_path, str) or relative_path in expected_paths:
            raise ReleaseVerificationError("release manifest has duplicate or invalid file paths")
        if entry.get("sha256") != _sha256(member):
            raise ReleaseVerificationError("release file SHA-256 does not match manifest: {0}".format(relative_path))
        if entry.get("size_bytes") != member.stat().st_size:
            raise ReleaseVerificationError("release file size does not match manifest: {0}".format(relative_path))
        expected_paths.add(relative_path)

    actual_paths = set()
    for path in release_dir.rglob("*"):
        if path.is_symlink():
            raise ReleaseVerificationError("release bundle must not contain symbolic links")
        if path.is_file() and path.name not in (MANIFEST_FILENAME, MANIFEST_DIGEST_FILENAME):
            actual_paths.add(path.relative_to(release_dir).as_posix())
    if expected_paths != actual_paths:
        raise ReleaseVerificationError("release manifest inventory does not match bundle contents")
    return len(expected_paths)


def _run_snapshot_replay(release_dir: Path, candidate_id: str) -> Dict[str, object]:
    """Load the frozen package and workspace in a clean Python subprocess.

    This executes the release's own source tree rather than the caller's
    checkout. It intentionally tests an offline replay boundary only: source
    import plus candidate metadata loading. Scientific engines are not rerun
    because their remote services and optional runtimes are not reproducible by
    a generic metadata verifier.
    """
    source_path = release_dir / "source" / "src"
    workspace_root = release_dir / "workspace"
    if not source_path.is_dir() or not workspace_root.is_dir():
        raise ReleaseVerificationError("release source or workspace snapshot is missing")
    script = (
        "import json, sys\n"
        "from pathlib import Path\n"
        "source = Path(sys.argv[1]).resolve()\n"
        "workspace_root = Path(sys.argv[2]).resolve()\n"
        "candidate_id = sys.argv[3]\n"
        "if sys.version_info[:2] < (3, 9):\n"
        "    raise RuntimeError('replay requires Python >= 3.9')\n"
        "sys.path.insert(0, str(source))\n"
        "import exonym\n"
        "module_path = Path(exonym.__file__).resolve()\n"
        "if source not in module_path.parents:\n"
        "    raise RuntimeError('did not import the frozen exonym source')\n"
        "from exonym.workspace import load_candidate\n"
        "candidate = load_candidate(workspace_root, candidate_id)\n"
        "if candidate.candidate_id != candidate_id:\n"
        "    raise RuntimeError('frozen workspace candidate mismatch')\n"
        "print(json.dumps({'package_path': str(module_path), 'candidate_id': candidate.candidate_id, 'python_version': '.'.join(map(str, sys.version_info[:3]))}, sort_keys=True))\n"
    )
    environment = os.environ.copy()
    environment.pop("PYTHONPATH", None)
    try:
        result = subprocess.run(
            [sys.executable, "-c", script, str(source_path), str(workspace_root), candidate_id],
            capture_output=True,
            check=False,
            env=environment,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise ReleaseVerificationError("release source replay could not start: {0}".format(exc)) from exc
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown replay failure"
        raise ReleaseVerificationError("release source replay failed: {0}".format(detail))
    try:
        replay = json.loads(result.stdout)
    except (TypeError, ValueError, json.JSONDecodeError) as exc:
        raise ReleaseVerificationError("release source replay did not return JSON: {0}".format(exc)) from exc
    if not isinstance(replay, dict) or replay.get("candidate_id") != candidate_id:
        raise ReleaseVerificationError("release source replay returned an invalid candidate record")
    return replay


def _collect_engine_manifests(workspace: CandidateWorkspace) -> List[Dict]:
    """Scan candidate runs/ and return a sorted list of engine-run manifest records.

    Each record contains:
    - ``engine``: the engine name from the manifest
    - ``run_id``: the run identifier
    - ``status``: succeeded / failed
    - ``manifest_path``: relative posix path from workspace root
    - ``sha256``: content hash of the manifest file

    Records are ordered by ``started_at`` ascending so that the release manifest
    reflects the full chronological analysis chain.
    """
    records: List[Dict] = []
    runs_dir = workspace.path / "runs"
    if not runs_dir.is_dir():
        return records

    for manifest_path in sorted(runs_dir.glob("*/*/engine-run.json")):
        if not manifest_path.is_file():
            continue
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        records.append({
            "engine": data.get("engine", "unknown"),
            "run_id": data.get("run_id", ""),
            "status": data.get("status", "unknown"),
            "started_at": data.get("started_at", ""),
            "manifest_path": manifest_path.relative_to(workspace.path).as_posix(),
            "sha256": _sha256(manifest_path),
        })

    # Sort by started_at timestamp so the chain is chronological
    records.sort(key=lambda r: r.get("started_at", ""))
    return records


def _collect_config_hashes(workspace: CandidateWorkspace) -> Dict[str, str]:
    """Hash every JSON file under candidate config/ and return a path→sha256 mapping.

    Config files contain the transit ephemeris priors that were active during the
    analysis. Including their hashes in the freeze manifest makes it possible to
    detect any ephemeris drift between the original run and a replay attempt.
    """
    hashes: Dict[str, str] = {}
    config_dir = workspace.path / "config"
    if not config_dir.is_dir():
        return hashes
    for p in sorted(config_dir.rglob("*.json")):
        if p.is_file():
            rel = p.relative_to(workspace.path).as_posix()
            hashes[rel] = _sha256(p)
    return hashes


def _collect_catalog_manifests(workspace: CandidateWorkspace) -> List[Dict]:
    """Index append-only catalog retrieval manifests for release reproducibility."""
    records: List[Dict] = []
    for manifest_path in sorted((workspace.path / "runs" / "catalog").glob("*/*/query-manifest.json")):
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError):
            continue
        if not isinstance(data, dict):
            continue
        records.append({
            "provider": data.get("provider", "unknown"),
            "retrieval_id": data.get("retrieval_id", ""),
            "status": data.get("status", "unknown"),
            "retrieved_at": data.get("retrieved_at", ""),
            "manifest_path": manifest_path.relative_to(workspace.path).as_posix(),
            "sha256": _sha256(manifest_path),
        })
    records.sort(key=lambda record: record.get("retrieved_at", ""))
    return records


def _require_valid_catalog_evidence(workspace: CandidateWorkspace) -> None:
    """Refuse to freeze candidate catalog evidence that fails repository validation."""
    catalog_runs = workspace.path / "runs" / "catalog"
    if not catalog_runs.is_dir():
        return
    from .isolation import IsolationReport
    from .schemas import validate_schemas

    report = IsolationReport()
    validate_schemas(workspace.repository_root, report)
    workspace_root = workspace.path.resolve()
    failures = []
    for violation in report.violations:
        try:
            path = Path(violation.path).resolve()
            path.relative_to(workspace_root)
        except (TypeError, ValueError):
            continue
        if "catalog" in path.parts:
            failures.append(violation)
    if failures:
        raise ValueError("cannot freeze invalid candidate-local catalog evidence: {0}".format(failures[0].detail))


def _copy_tree(source: Path, destination: Path, ignore=None) -> None:
    """Copy a source tree without sharing mutable files with the release."""
    shutil.copytree(source, destination, copy_function=shutil.copy2, ignore=ignore)


def _snapshot_source(repository_root: Path, bundle_dir: Path) -> Dict[str, object]:
    """Copy the exact package source required by generated replay environments."""
    pyproject = repository_root / "pyproject.toml"
    source_tree = repository_root / "src"
    if not pyproject.is_file() or not source_tree.is_dir():
        raise FileNotFoundError(
            "self-contained freeze requires repository pyproject.toml and src/"
        )
    destination = bundle_dir / "source"
    destination.mkdir()
    shutil.copy2(pyproject, destination / "pyproject.toml")
    _copy_tree(source_tree, destination / "src")
    for name in ("README.md", "LICENSE", "LICENSE.md"):
        source = repository_root / name
        if source.is_file():
            shutil.copy2(source, destination / name)
    return {
        "path": "source",
        "package_definition": "source/pyproject.toml",
        "package_source": "source/src",
    }


def _snapshot_workspace(workspace: CandidateWorkspace, repository_root: Path, bundle_dir: Path) -> Dict[str, object]:
    """Copy a root-shaped candidate evidence snapshot without recursive releases."""
    destination = bundle_dir / "workspace"
    candidate_destination = destination / "candidate" / workspace.candidate_id
    candidate_destination.parent.mkdir(parents=True)

    def ignore_snapshot_entries(_directory: str, names: List[str]) -> List[str]:
        return [name for name in names if name in _WORKSPACE_SNAPSHOT_EXCLUDES]

    _copy_tree(workspace.path, candidate_destination, ignore=ignore_snapshot_entries)
    for resource_name in ("schemas", "templates"):
        source = repository_root / resource_name
        if source.is_dir():
            _copy_tree(source, destination / resource_name)
    return {
        "path": "workspace",
        "candidate_path": "workspace/candidate/{0}".format(workspace.candidate_id),
        "excluded_paths": sorted(_WORKSPACE_SNAPSHOT_EXCLUDES),
    }


def verify_release(workspace: CandidateWorkspace, version: str) -> Dict[str, object]:
    """Verify one frozen bundle and execute its offline source/workspace replay.

    The check is deliberately narrower than a scientific rerun: it proves that
    the detached manifest, every bundled byte, the snapshot package, and the
    candidate metadata can be replayed without consulting the live checkout or
    a network service. It does not re-execute scientific engines or recreate a
    remote catalogue response.

    Args:
        workspace: Candidate workspace that owns the requested release.
        version: Directory-safe frozen release version.

    Returns:
        Release identity, detached-manifest digest, verified file count, and
        offline replay metadata.

    Raises:
        FileNotFoundError: If the requested release is absent.
        ReleaseVerificationError: If integrity, inventory, lock, or offline
            replay checks fail.
    """
    version = _validate_release_version(version)
    release_dir = workspace.path / "releases" / version
    if not release_dir.is_dir() or release_dir.is_symlink():
        raise FileNotFoundError("release not found: {0}".format(release_dir))
    manifest_sha256 = _verify_detached_manifest_digest(release_dir)
    manifest = _read_release_manifest(release_dir / MANIFEST_FILENAME)
    if manifest.get("schema") != "exonym-freeze-3":
        raise ReleaseVerificationError("release manifest schema must be exonym-freeze-3")
    if manifest.get("version") != version or manifest.get("candidate_id") != workspace.candidate_id:
        raise ReleaseVerificationError("release manifest does not match the requested candidate and version")
    lock_path = release_dir / REQUIREMENTS_LOCK_FILENAME
    if not lock_path.is_file() or lock_path.is_symlink():
        raise ReleaseVerificationError("release requirements lock is missing")
    pinned_packages = _read_pinned_requirements(lock_path)
    lock_metadata = manifest.get("requirements_lock")
    if (
        not isinstance(lock_metadata, dict)
        or lock_metadata.get("format") != "fully-pinned-requirements"
        or lock_metadata.get("package_count") != len(pinned_packages)
        or lock_metadata.get("sha256") != _sha256(lock_path)
    ):
        raise ReleaseVerificationError("release requirements lock metadata does not match the bundled lock")
    if manifest.get("requirements_lock_sha256") != _sha256(lock_path):
        raise ReleaseVerificationError("release requirements lock SHA-256 does not match the manifest")
    source_project = release_dir / "source" / "pyproject.toml"
    if not source_project.is_file() or manifest.get("source_pyproject_toml_sha256") != _sha256(source_project):
        raise ReleaseVerificationError("release source package definition does not match the manifest")
    candidate_metadata = release_dir / "workspace" / "candidate" / workspace.candidate_id / METADATA_FILENAME
    if not candidate_metadata.is_file() or manifest.get("candidate_json_sha256") != _sha256(candidate_metadata):
        raise ReleaseVerificationError("release candidate snapshot does not match the manifest")
    checked_file_count = _verify_release_inventory(release_dir, manifest)
    replay = _run_snapshot_replay(release_dir, workspace.candidate_id)
    return {
        "candidate_id": workspace.candidate_id,
        "version": version,
        "manifest_sha256": manifest_sha256,
        "checked_file_count": checked_file_count,
        "replay": replay,
    }


def freeze(workspace: CandidateWorkspace, version: Optional[str] = None) -> Path:
    """Build the reproducibility bundle and return its directory.

    The release manifest includes:
    - Fully pinned dependency lock metadata and hash
    - Git commit at freeze time
    - candidate.json hash
    - Engine run manifest index (all runs/<engine>/<run-id>/engine-run.json)
    - Transit config file hashes (config/**/*.json)
    - pyproject.toml hash (repository-level package definition)

    Args:
        workspace: Candidate workspace whose evidence is snapshotted.
        version: Optional safe release label; a timestamp-based label is used
            when omitted.

    Returns:
        Directory containing the completed candidate-local release bundle.

    Raises:
        FileExistsError: If the requested release directory already exists.
        FileNotFoundError: If the root requirements lock is absent.
        ValueError: If the version, dependency lock, or catalog evidence does
            not satisfy the release contract.

    Note:
        The bundle is an integrity-checked snapshot, not a scientific rerun
        or proof that optional engines and external services are reproducible.
    """
    version = _validate_release_version(version or _default_version())
    release_dir = workspace.path / "releases" / version
    if release_dir.exists():
        raise FileExistsError("release already exists: {0}".format(release_dir))
    repository_root = workspace.repository_root
    lock_source = repository_root / "requirements-lock.txt"
    if not lock_source.is_file():
        raise FileNotFoundError("root requirements-lock.txt not found: {0}".format(lock_source))
    lock_packages = _read_pinned_requirements(lock_source)
    _require_valid_catalog_evidence(workspace)
    bundle_dir = release_dir.parent / ".{0}.staging-{1}".format(version, uuid4().hex)
    bundle_dir.mkdir(parents=True)
    try:
        bundled_lock = bundle_dir / REQUIREMENTS_LOCK_FILENAME
        shutil.copyfile(lock_source, bundled_lock)
        source_snapshot = _snapshot_source(repository_root, bundle_dir)
        workspace_snapshot = _snapshot_workspace(workspace, repository_root, bundle_dir)
        (bundle_dir / "README.md").write_text(RELEASE_README_TEMPLATE, encoding="utf-8")

        pip_entries = []
        for line in lock_packages:
            pip_entries.append('      - "{0}"'.format(line))
        pip_entries.append('      - "-e ./source"')
        environment = (
            ENVIRONMENT_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
            .replace("{pip_entries}", "\n".join(pip_entries))
        )
        (bundle_dir / "environment.lock.yml").write_text(environment, encoding="utf-8")

        dockerfile = DOCKERFILE_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
        (bundle_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")
        apptainer = APPTAINER_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
        (bundle_dir / "Apptainer.def").write_text(apptainer, encoding="utf-8")

        metadata_path = workspace.path / METADATA_FILENAME
        files: List[Dict] = []
        for path in sorted(bundle_dir.rglob("*")):
            if path.is_file():
                files.append(
                    {
                        "path": path.relative_to(bundle_dir).as_posix(),
                        "size_bytes": path.stat().st_size,
                        "sha256": _sha256(path),
                    }
                )

        manifest = {
            "schema": "exonym-freeze-3",
            "version": version,
            "candidate_id": workspace.candidate_id,
            "frozen_at": _now(),
            "git_commit": _git_commit(repository_root),
            "candidate_json_sha256": _sha256(metadata_path),
            "engine_manifests": _collect_engine_manifests(workspace),
            "config_hashes": _collect_config_hashes(workspace),
            "catalog_manifests": _collect_catalog_manifests(workspace),
            "pyproject_toml_sha256": _sha256(repository_root / "pyproject.toml"),
            "source_pyproject_toml_sha256": _sha256(bundle_dir / "source" / "pyproject.toml"),
            "requirements_lock_sha256": _sha256(lock_source),
            "requirements_lock": {
                "format": "fully-pinned-requirements",
                "package_count": len(lock_packages),
                "sha256": _sha256(bundled_lock),
            },
            "replay_status": "integrity-checked-source-import-and-workspace-load",
            "source_snapshot": source_snapshot,
            "workspace_snapshot": workspace_snapshot,
            "files": files,
        }
        manifest_path = bundle_dir / MANIFEST_FILENAME
        manifest_path.write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (bundle_dir / MANIFEST_DIGEST_FILENAME).write_text(
            "{0}  {1}\n".format(_sha256(manifest_path), MANIFEST_FILENAME), encoding="ascii"
        )
        bundle_dir.replace(release_dir)
    except Exception:
        shutil.rmtree(bundle_dir, ignore_errors=True)
        raise
    return release_dir
